export enum EnemyTypes {
	SEARCH_ENEMIES_START = 'SEARCH_ENEMIES_START',
	SEARCH_ENEMIES_SUCCESS = 'SEARCH_ENEMIES_SUCCESS',
	SEND_ENEMY_REQUEST = 'SEND_ENEMY_REQUEST',
	FETCH_ENEMY_INFO_START = 'FETCH_ENEMY_INFO_START',
	FETCH_ENEMY_INFO_SUCCESS = 'FETCH_ENEMY_INFO_SUCCESS',
	ENEMY_ERROR = 'ENEMY_ERROR',
}
