export enum NotificationTypes {
	OPEN_NOTIFICATION_LISTENER = 'OPEN_NOTIFICATION_LISTENER',
	NEW_NOTIFICATION = 'NEW_NOTIFICATION',
	DELETE_NOTIFICATION = 'DELETE_NOTIFICATION',
	READ_NOTIFICATION = 'READ_NOTIFICATION',
}
