enum UserTypes {
	CHECK_USER_SESSION = 'CHECK_USER_SESSION',
	LOG_OUT_START = 'LOG_OUT_START',
	LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS',
	LOG_IN_START = 'LOG_IN_START',
	LOG_IN_SUCCESS = 'LOG_IN_SUCCESS',
	CREATE_ACCOUNT_START = 'CREATE_ACCOUNT_START',
	CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS',
	UPDATE_DISPLAY_NAME = 'UPDATE_DISPLAY_NAME',
	UPDATE_PROFILE_INFO = 'UPDATE_PROFILE_INFO',
	UPDATE_EMAIL = 'UPDATE_EMAIL',
	UPDATE_PASSWORD = 'UPDATE_PASSWORD',
	FETCH_USER_PROFILE = 'FETCH_USER_PROFILE',
	DELETE_USER_ACCOUNT = 'DELETE_USER_ACCOUNT',
	USER_ERROR = 'USER_ERROR',
}

export default UserTypes;
